import './style.css';

let excelModulePromise;
async function getExcelJS() {
  excelModulePromise ||= import('exceljs').then((module) => module.default ?? module);
  return excelModulePromise;
}

const SUPABASE_URL = 'https://oedasgcdjppjwidhlqdr.supabase.co';
const SUPABASE_ANON_KEY = 'sb_publishable_LGgDehtHMSyeJ1XyJDvQiQ_cdlqIKq7';
const API_BASE = `${SUPABASE_URL}/functions/v1/web-api`;
const SESSION_KEY = 'bao-hang-1291-web-session';
const MAX_FILE_BYTES = 15 * 1024 * 1024;
const ROLES = { ADMIN: 'Admin', ADMIN_INVENT: 'Admin Invent', INVENT: 'Báo hàng Invent', PICKER: 'Người lấy hàng' };
const state = { session: null, testRole: null, selectedSku: null, pollTimer: null, activeTab: null, managedUsers: [] };
const $ = (s, r = document) => r.querySelector(s);
const $$ = (s, r = document) => [...r.querySelectorAll(s)];

function normalize(value) { return String(value ?? '').trim().normalize('NFD').replace(/\p{M}+/gu, '').toLowerCase().replaceAll('đ', 'd').replace(/\s+/g, ' '); }
function escapeHtml(value) { return String(value ?? '').replace(/[&<>'"]/g, (c) => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' }[c])); }
function employeeEmail(code) { const raw=String(code??'').trim().toLowerCase(); if(!raw||!/^[a-z0-9._-]+$/.test(raw)) throw new Error('Mã nhân viên không hợp lệ.'); return `${raw}@bao-hang-1291.local`; }
function role(){return state.testRole||state.session?.profile?.role||'PICKER';}
function actualRole(){return state.session?.profile?.role||'PICKER';}

function readSession(){try{const p=JSON.parse(sessionStorage.getItem(SESSION_KEY)||'null');return p?.access_token&&p?.refresh_token&&p?.profile?p:null;}catch{return null;}}
function saveSession(s){state.session=s;sessionStorage.setItem(SESSION_KEY,JSON.stringify(s));}
function clearSession(){state.session=null;state.testRole=null;sessionStorage.removeItem(SESSION_KEY);clearInterval(state.pollTimer);state.pollTimer=null;}
async function parseResponse(r){const t=await r.text();let d={};if(t){try{d=JSON.parse(t);}catch{d={error:t};}}if(!r.ok)throw new Error(d.error||d.message||`Lỗi máy chủ ${r.status}`);return d;}
async function authToken(payload,grantType='password'){return parseResponse(await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=${grantType}`,{method:'POST',headers:{'content-type':'application/json',apikey:SUPABASE_ANON_KEY},body:JSON.stringify(payload)}));}
async function fetchProfile(accessToken,userId){const q=new URLSearchParams({id:`eq.${userId}`,select:'id,employee_code,full_name,contractor,role,active'});const rows=await parseResponse(await fetch(`${SUPABASE_URL}/rest/v1/profiles?${q}`,{headers:{apikey:SUPABASE_ANON_KEY,authorization:`Bearer ${accessToken}`}}));if(!Array.isArray(rows)||!rows.length)throw new Error('Tài khoản chưa có hồ sơ nhân sự.');return rows[0];}
async function refreshSessionIfNeeded(){if(!state.session)throw new Error('Phiên đăng nhập không tồn tại.');const now=Math.floor(Date.now()/1000);if((state.session.expires_at||0)>now+120)return;const t=await authToken({refresh_token:state.session.refresh_token},'refresh_token');saveSession({...state.session,access_token:t.access_token,refresh_token:t.refresh_token||state.session.refresh_token,expires_at:now+Number(t.expires_in||3600)});}
async function api(action,payload={}){await refreshSessionIfNeeded();const h={'content-type':'application/json',apikey:SUPABASE_ANON_KEY,authorization:`Bearer ${state.session.access_token}`};if(state.testRole)h['x-admin-test-role']=state.testRole;const r=await fetch(`${API_BASE}/${encodeURIComponent(action)}`,{method:'POST',headers:h,body:JSON.stringify(payload)});if(r.status===401){clearSession();renderLogin('Phiên đăng nhập đã hết hạn.');throw new Error('Phiên đăng nhập đã hết hạn.');}return parseResponse(r);}
function setBusy(busy,text='Đang xử lý…'){const el=$('#busy');if(!el)return;el.hidden=!busy;$('#busyText').textContent=text;}
function message(id,text,type='info'){const el=typeof id==='string'?$(id):id;if(!el)return;el.textContent=text;el.dataset.type=type;el.hidden=!text;}

function renderLogin(msg=''){
  clearInterval(state.pollTimer);state.pollTimer=null;
  document.body.innerHTML=`<main class="login-shell"><section class="login-card"><div class="brand">1291</div><p class="eyebrow">BÁO HÀNG 1291</p><h1>Web nghiệp vụ</h1><p class="muted">Đăng nhập bằng tài khoản đang dùng trên ứng dụng.</p><form id="loginForm"><label>Mã nhân viên<input id="employeeCode" required autocomplete="username"></label><label>Mật khẩu<input id="password" type="password" required autocomplete="current-password"></label><button class="primary wide">ĐĂNG NHẬP</button></form><div id="loginMessage" class="message" hidden></div><p class="security">Quyền được kiểm tra tại server. Web không chứa service-role key hoặc private key.</p></section></main>`;
  if(msg)message('#loginMessage',msg,'error');$('#loginForm').addEventListener('submit',handleLogin);$('#employeeCode').focus();
}
async function handleLogin(e){e.preventDefault();const b=e.submitter;b.disabled=true;message('#loginMessage','Đang xác thực…');try{const t=await authToken({email:employeeEmail($('#employeeCode').value),password:$('#password').value});const p=await fetchProfile(t.access_token,t.user.id);if(!p.active)throw new Error('Tài khoản đã ngừng hoạt động.');saveSession({access_token:t.access_token,refresh_token:t.refresh_token,expires_at:Math.floor(Date.now()/1000)+Number(t.expires_in||3600),profile:p});state.testRole=null;renderApp();}catch(err){message('#loginMessage',err.message,'error');}finally{b.disabled=false;}}

function tabsForRole(r){if(r==='ADMIN')return[['overview','Tổng quan'],['operations','Báo hàng'],['picker','Lấy hàng'],['reports','Báo cáo'],['logs','Log'],['sku','SKU'],['users','Nhân sự'],['config','Cấu hình']];if(r==='ADMIN_INVENT')return[['overview','Tổng quan'],['operations','Báo hàng'],['reports','Báo cáo'],['logs','Log'],['sku','SKU'],['users','Nhân sự']];if(r==='INVENT')return[['operations','Báo hàng']];return[['picker','Lấy hàng']];}
function renderApp(){
  clearInterval(state.pollTimer);state.pollTimer=null;const p=state.session.profile,r=role(),tabs=tabsForRole(r);state.activeTab=tabs.some(([id])=>id===state.activeTab)?state.activeTab:tabs[0][0];
  document.body.innerHTML=`<div class="app-shell"><header class="topbar"><div><p class="eyebrow">BÁO HÀNG 1291</p><h1>Web nghiệp vụ</h1></div><div class="user"><strong>${escapeHtml(p.full_name)}</strong><span>${escapeHtml(p.employee_code)} · ${escapeHtml(ROLES[r]||r)}</span><button id="logout" class="ghost">Đăng xuất</button></div></header>${state.testRole?`<div class="test-banner">ĐANG KIỂM THỬ QUYỀN: <strong>${escapeHtml(ROLES[state.testRole])}</strong> · API cũng đang bị giới hạn theo quyền này. <button id="exitTest">Thoát kiểm thử</button></div>`:''}${actualRole()==='ADMIN'&&!state.testRole?`<div class="test-tools"><span>Kiểm thử giao diện thực tế:</span><button data-test="ADMIN_INVENT">Admin Invent</button><button data-test="INVENT">Báo hàng Invent</button><button data-test="PICKER">Người lấy hàng</button></div>`:''}<nav class="tabs">${tabs.map(([id,l])=>`<button data-tab="${id}" class="${id===state.activeTab?'active':''}">${l}</button>`).join('')}</nav><main id="content" class="content"></main></div><div id="busy" class="busy" hidden><div><span class="spinner"></span><strong id="busyText">Đang xử lý…</strong></div></div>`;
  $('#logout').onclick=()=>{clearSession();renderLogin();};$('#exitTest')?.addEventListener('click',()=>{state.testRole=null;state.activeTab=null;renderApp();});$$('[data-test]').forEach(b=>b.onclick=()=>{state.testRole=b.dataset.test;state.activeTab=null;renderApp();});$$('[data-tab]').forEach(b=>b.onclick=()=>{state.activeTab=b.dataset.tab;renderTab();});renderTab();if(r==='PICKER')startAlertPolling();
}
function renderTab(){ $$('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.activeTab));({overview:renderOverview,operations:renderOperations,picker:renderPicker,reports:renderReports,logs:renderLogs,sku:renderSku,users:renderUsers,config:renderConfig})[state.activeTab]?.(); }

async function renderOverview(){
  $('#content').innerHTML=`<div class="heading"><div><p class="eyebrow">LIVE</p><h2>Tổng quan hệ thống</h2></div><button id="refresh" class="secondary">Làm mới</button></div><div id="metrics" class="metrics"></div><div class="card"><h3>Google Sheet</h3><button id="syncSheet" class="secondary">ĐỒNG BỘ NGAY</button><div id="overviewMsg" class="message" hidden></div></div>`;$('#refresh').onclick=renderOverview;$('#syncSheet').onclick=async()=>{try{setBusy(true,'Đang đồng bộ Google Sheet…');const r=await api('sync-google-sheet');message('#overviewMsg',`Đã xuất ${r.exported||0}; còn ${r.remaining||0} sự kiện.`,'good');}catch(e){message('#overviewMsg',e.message,'error');}finally{setBusy(false);}};
  try{const d=await api('admin-summary');$('#metrics').innerHTML=[['SKU',d.sku_count],['Nhân sự hoạt động',d.active_user_count],['Báo thiếu đang mở',d.active_issue_count],['Chờ Google Sheet',d.pending_sheet_count],['Log chẩn đoán',d.diagnostic_log_count]].map(([l,v])=>`<article class="metric"><span>${l}</span><strong>${Number(v||0).toLocaleString('vi-VN')}</strong></article>`).join('');}catch(e){$('#metrics').innerHTML=`<div class="message" data-type="error">${escapeHtml(e.message)}</div>`;}
}

async function renderOperations(){
  $('#content').innerHTML=`<div class="heading"><div><p class="eyebrow">INVENT</p><h2>Xử lý báo hàng</h2></div><button id="refreshBoard" class="secondary">Làm mới</button></div><div class="subtabs"><button data-bucket="open" class="active">BÁO THIẾU</button><button data-bucket="skipped">SKIP</button><button data-bucket="available">ĐÃ CHÂM BÙ</button></div><div id="board"></div>`;let board=null,bucket='open';
  const draw=()=>{const rows=board?.[bucket]||[];$('#board').innerHTML=rows.length?rows.map(i=>issueCardHtml(i,bucket)).join(''):`<div class="card muted">Không có SKU ở trạng thái này.</div>`;$$('[data-issue-action]').forEach(b=>b.onclick=()=>issueAction(b.dataset.issueId,b.dataset.issueAction,b.dataset.sku,load));$$('[data-claim]').forEach(b=>b.onclick=()=>claimIssue(b.dataset.claim,load));};
  const load=async()=>{try{setBusy(true,'Đang tải báo hàng…');board=await api('issue-board');draw();}catch(e){$('#board').innerHTML=`<div class="message" data-type="error">${escapeHtml(e.message)}</div>`;}finally{setBusy(false);}};$('#refreshBoard').onclick=load;$$('[data-bucket]').forEach(b=>b.onclick=()=>{bucket=b.dataset.bucket;$$('[data-bucket]').forEach(x=>x.classList.toggle('active',x===b));draw();});load();
}
function issueCardHtml(i,b){const a=i.assigned_name?` · Xử lý: ${escapeHtml(i.assigned_name)}`:'';const c=`<article class="card issue"><div class="issue-top"><div><strong>SKU ${escapeHtml(i.sku)}</strong><span>${Number(i.report_count||1)} lượt báo</span></div><time>${formatTime(i.reported_at)}</time></div><p>${escapeHtml(i.product_name)}</p><small>Báo đầu: ${formatTime(i.reported_at)}${a}</small>`;if(b==='open')return`${c}<div class="actions">${!i.assigned_name?`<button class="secondary" data-claim="${i.id}">Nhận xử lý</button>`:''}<button class="danger" data-issue-action="NOT_FOUND" data-issue-id="${i.id}" data-sku="${escapeHtml(i.sku)}">SKIP</button><button class="primary" data-issue-action="AVAILABLE" data-issue-id="${i.id}" data-sku="${escapeHtml(i.sku)}">ĐÃ CHÂM BÙ</button></div></article>`;if(b==='skipped')return`${c}<div class="actions"><button class="primary" data-issue-action="AVAILABLE" data-issue-id="${i.id}" data-sku="${escapeHtml(i.sku)}">ĐÃ TÌM THẤY / CHÂM BÙ</button></div></article>`;return`${c}</article>`;}
async function claimIssue(id,done){try{setBusy(true,'Đang khóa SKU cho người xử lý…');await api('claim-issue',{issue_id:id});await done();}catch(e){alert(e.message);}finally{setBusy(false);}}
async function issueAction(id,action,sku,done){const l=action==='NOT_FOUND'?`Cho phép Picker SKIP SKU ${sku}?`:`Xác nhận SKU ${sku} đã có hàng/châm bù?`;if(!confirm(l))return;try{setBusy(true,'Đang cập nhật và gửi thông báo…');await api('update-issue',{issue_id:id,action});await done();}catch(e){alert(e.message);}finally{setBusy(false);}}

function renderPicker(){
  $('#content').innerHTML=`<div class="heading"><div><p class="eyebrow">PICKER</p><h2>Người lấy hàng</h2></div></div><div class="card"><label>Tìm bất kỳ phần nào của SKU hoặc tên hàng<input id="skuSearch" placeholder="Ví dụ: b, c, cd…"></label><div id="skuResults" class="search-results"></div><div id="selectedSku" class="selected muted">Chưa chọn SKU</div><button id="reportShortage" class="danger wide" disabled>BÁO THIẾU</button><div id="pickerMsg" class="message" hidden></div></div><div class="heading compact"><h3>Báo thiếu của tôi</h3><button id="refreshMine" class="secondary">Làm mới</button></div><div id="myIssues"></div><div id="pendingAlert"></div>`;let timer;state.selectedSku=null;$('#skuSearch').addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(searchSku,120);});$('#reportShortage').onclick=reportShortage;$('#refreshMine').onclick=loadMyIssues;loadMyIssues();loadPendingAlerts();
}
async function searchSku(){const q=$('#skuSearch')?.value.trim();if(!q){$('#skuResults').innerHTML='';return;}try{const d=await api('search-skus',{query:q,limit:20});$('#skuResults').innerHTML=(d.items||[]).map((x,i)=>`<button data-result="${i}"><strong>${escapeHtml(x.sku)}</strong><span>${escapeHtml(x.product_name)}</span></button>`).join('');$$('[data-result]').forEach(b=>b.onclick=()=>{const i=d.items[Number(b.dataset.result)];state.selectedSku=i;$('#selectedSku').innerHTML=`<strong>SKU ${escapeHtml(i.sku)}</strong><span>${escapeHtml(i.product_name)}</span>`;$('#selectedSku').classList.remove('muted');$('#reportShortage').disabled=false;$('#skuResults').innerHTML='';});}catch(e){message('#pickerMsg',e.message,'error');}}
async function reportShortage(){if(!state.selectedSku)return;if(!confirm(`Báo thiếu SKU ${state.selectedSku.sku}?`))return;try{setBusy(true,'Đang báo nhóm Invent…');const r=await api('report-shortage',{sku:state.selectedSku.sku,client_request_id:crypto.randomUUID()});message('#pickerMsg',(r.already_reported?'SKU đã được báo trước. ':'')+(r.message||'Đã báo thiếu'),'good');await loadMyIssues();}catch(e){message('#pickerMsg',e.message,'error');}finally{setBusy(false);}}
async function loadMyIssues(){if(!$('#myIssues'))return;try{const d=await api('my-issues');$('#myIssues').innerHTML=(d.issues||[]).length?(d.issues||[]).map(i=>`<article class="card issue"><strong>${statusLabel(i.status)} · SKU ${escapeHtml(i.sku)}</strong><p>${escapeHtml(i.product_name)}</p><small>${Number(i.report_count||1)} lượt · ${formatTime(i.reported_at)}</small></article>`).join(''):'<div class="card muted">Chưa có báo thiếu.</div>';}catch(e){$('#myIssues').innerHTML=`<div class="message" data-type="error">${escapeHtml(e.message)}</div>`;}}
function startAlertPolling(){clearInterval(state.pollTimer);loadPendingAlerts();state.pollTimer=setInterval(loadPendingAlerts,15000);}
async function loadPendingAlerts(){if(!$('#pendingAlert'))return;try{const d=await api('pending-alerts'),e=(d.events||[])[0];if(!e){$('#pendingAlert').innerHTML='';return;}$('#pendingAlert').innerHTML=`<div class="alert-modal"><div><p class="eyebrow">CẦN XÁC NHẬN</p><h2>${escapeHtml(e.title||statusLabel(e.status))}</h2><p>${escapeHtml(e.message)}</p><button id="ackAlert" class="primary wide">ĐÃ HIỂU</button></div></div>`;$('#ackAlert').onclick=async()=>{try{await api('ack-alert',{event_id:e.id});$('#pendingAlert').innerHTML='';}catch(err){alert(err.message);}};}catch(e){console.warn(e);}}

async function renderReports(){
  $('#content').innerHTML=`<div class="heading"><div><p class="eyebrow">30 NGÀY</p><h2>Báo cáo & lịch sử</h2></div><button id="refreshReports" class="secondary">Làm mới</button></div><div id="reportMetrics" class="metrics"></div><div class="panel-grid"><div class="card"><h3>SKU báo nhiều</h3><div id="topSkus"></div></div><div class="card"><h3>Lịch sử gần nhất</h3><div id="history"></div></div></div>`;$('#refreshReports').onclick=renderReports;
  try{const[r,h]=await Promise.all([api('reports-summary'),api('issue-history',{limit:100})]),s=r.by_status||{},open=(s.OPEN||0)+(s.CLAIMED||0)+(s.SEARCHING||0)+(s.REPLENISHING||0);$('#reportMetrics').innerHTML=[['Đợt báo thiếu',r.issues],['Tổng lượt báo',r.reports],['Đang mở',open],['SKIP',s.SKIP_ALLOWED||0],['Đã châm bù',s.AVAILABLE||0],['Xử lý TB',r.average_resolution_minutes==null?'—':`${r.average_resolution_minutes} phút`]].map(([l,v])=>`<article class="metric"><span>${l}</span><strong>${escapeHtml(v)}</strong></article>`).join('');$('#topSkus').innerHTML=(r.top_skus||[]).map(x=>`<div class="row"><strong>${escapeHtml(x.sku)}</strong><span>${x.reports} lượt</span></div>`).join('')||'<span class="muted">Chưa có dữ liệu</span>';$('#history').innerHTML=(h.issues||[]).slice(0,50).map(i=>`<div class="row"><span><strong>${escapeHtml(i.sku)}</strong> · ${statusLabel(i.status)}</span><time>${formatTime(i.reported_at)}</time></div>`).join('')||'<span class="muted">Chưa có dữ liệu</span>';}catch(e){$('#content').insertAdjacentHTML('beforeend',`<div class="message" data-type="error">${escapeHtml(e.message)}</div>`);}
}

async function renderLogs(){
  $('#content').innerHTML=`<div class="heading"><div><p class="eyebrow">CHẨN ĐOÁN</p><h2>Log thiết bị</h2></div><button id="refreshLogs" class="secondary">Làm mới</button></div><div class="card"><label>Lọc mã nhân viên<input id="logFilter" placeholder="Mã nhân viên"></label><button id="filterLogs" class="secondary">Tìm</button><p class="muted">Log private, tự xóa sau 14 ngày. Link tải chỉ có hiệu lực ngắn hạn.</p></div><div id="logs"></div>`;$('#refreshLogs').onclick=()=>loadLogs('');$('#filterLogs').onclick=()=>loadLogs($('#logFilter').value);await loadLogs('');
}
async function loadLogs(employee){try{const d=await api('list-logs',{limit:300,employee_code:employee||''});$('#logs').innerHTML=(d.logs||[]).map(l=>`<article class="card log"><div><strong>${escapeHtml(l.employee_code)} · ${escapeHtml(ROLES[l.role]||l.role)}</strong><span>${escapeHtml(l.device_name||'Thiết bị Android')}</span><small>${escapeHtml(l.app_version)} · ${formatBytes(l.compressed_bytes)} · ${formatTime(l.created_at)}</small></div><button data-log="${l.id}" class="secondary">Tải log</button></article>`).join('')||'<div class="card muted">Chưa có log.</div>';$$('[data-log]').forEach(b=>b.onclick=()=>downloadLog(b.dataset.log));}catch(e){$('#logs').innerHTML=`<div class="message" data-type="error">${escapeHtml(e.message)}</div>`;}}
async function downloadLog(id){try{setBusy(true,'Đang tạo link tải bảo mật…');const d=await api('download-log',{id});window.location.assign(d.url);}catch(e){alert(e.message);}finally{setBusy(false);}}

function renderSku(){
  $('#content').innerHTML=`<div class="heading"><div><p class="eyebrow">DANH MỤC</p><h2>Import SKU Excel</h2></div><button id="skuTemplate" class="secondary">Tải file mẫu</button></div><div class="card"><input id="skuFile" type="file" accept=".xlsx"><p class="muted">Cột bắt buộc: SKU, Tên sản phẩm. Trùng SKU được gộp; không tự xóa SKU vắng trong file mới.</p><div id="skuMsg" class="message" hidden></div></div><div id="skuPreview"></div>`;$('#skuFile').onchange=e=>previewSku(e.target.files?.[0]);$('#skuTemplate').onclick=downloadSkuTemplate;
}
async function previewSku(file){if(!file)return;try{validateFile(file);setBusy(true,'Đang đọc Excel…');const rows=parseSkuRows(await readWorkbook(file));$('#skuPreview').innerHTML=previewTable(rows.slice(0,100),['sku','product_name'],`${rows.length} SKU hợp lệ`)+`<button id="confirmSku" class="primary">XÁC NHẬN IMPORT ${rows.length} SKU</button>`;$('#confirmSku').onclick=()=>importSku(rows);}catch(e){message('#skuMsg',e.message,'error');}finally{setBusy(false);}}
async function importSku(rows){try{setBusy(true,'Đang import SKU…');let done=0;for(let i=0;i<rows.length;i+=1000){await api('import-skus',{items:rows.slice(i,i+1000)});done+=Math.min(1000,rows.length-i);$('#busyText').textContent=`Đã import ${done}/${rows.length} SKU…`;}message('#skuMsg',`Hoàn tất ${rows.length} SKU.`,'good');$('#skuPreview').innerHTML='';}catch(e){message('#skuMsg',e.message,'error');}finally{setBusy(false);}}

function renderUsers(){
  const canImport=role()==='ADMIN';
  $('#content').innerHTML=`<div class="heading"><div><p class="eyebrow">NHÂN SỰ</p><h2>Quản lý tài khoản</h2></div><button id="refreshUsers" class="secondary">Làm mới</button></div><div class="card"><p class="muted">Admin sửa mọi tài khoản; ADMIN duy nhất vẫn được bảo vệ. Admin Invent chỉ sửa tài khoản Báo hàng Invent và Người lấy hàng.</p><div id="managedUsers"></div></div>${canImport?`<div class="heading compact"><h3>Import nhân sự</h3><button id="userTemplate" class="secondary">Tải file mẫu</button></div><div class="card"><input id="userFile" type="file" accept=".xlsx"><p class="muted">Vai trò import: ADMIN_INVENT, INVENT, PICKER. ADMIN hiện tại không thể tạo thêm, hạ quyền hoặc vô hiệu hóa.</p><div id="userMsg" class="message" hidden></div></div><div id="userPreview"></div>`:''}`;
  $('#refreshUsers').onclick=loadManagedUsers;
  if(canImport){$('#userFile').onchange=e=>previewUsers(e.target.files?.[0]);$('#userTemplate').onclick=downloadUserTemplate;}
  loadManagedUsers();
}
async function loadManagedUsers(){
  try{const d=await api('list-users');state.managedUsers=d.users||[];$('#managedUsers').innerHTML=state.managedUsers.map(u=>{const editable=role()==='ADMIN'||(role()==='ADMIN_INVENT'&&['INVENT','PICKER'].includes(u.role));return`<div class="row"><span><strong>${escapeHtml(u.employee_code)} · ${escapeHtml(u.full_name)}</strong><br><small>${escapeHtml(ROLES[u.role]||u.role)} · ${u.active?'Đang hoạt động':'Đã khóa'}${u.contractor?` · ${escapeHtml(u.contractor)}`:''}</small></span>${editable?`<button class="secondary" data-edit-user="${u.id}">Chỉnh sửa</button>`:''}</div>`;}).join('')||'<span class="muted">Chưa có tài khoản.</span>';$$('[data-edit-user]').forEach(b=>b.onclick=()=>openUserEditor(b.dataset.editUser));}catch(e){$('#managedUsers').innerHTML=`<div class="message" data-type="error">${escapeHtml(e.message)}</div>`;}
}
function openUserEditor(id){
  const u=state.managedUsers.find(x=>x.id===id);if(!u)return;const allowed=u.role==='ADMIN'?['ADMIN']:(role()==='ADMIN'?['ADMIN_INVENT','INVENT','PICKER']:['INVENT','PICKER']);
  document.body.insertAdjacentHTML('beforeend',`<div class="alert-modal" id="userEditorModal"><div class="card"><p class="eyebrow">CHỈNH SỬA NHÂN SỰ</p><h2>${escapeHtml(u.employee_code)}</h2><form id="editUserForm" class="form-grid"><label>Mã nhân viên<input id="editCode" value="${escapeHtml(u.employee_code)}" required></label><label>Họ tên<input id="editName" value="${escapeHtml(u.full_name)}" required></label><label>Nhà thầu<input id="editContractor" value="${escapeHtml(u.contractor||'')}"></label><label>Quyền<select id="editRole" ${u.role==='ADMIN'?'disabled':''}>${allowed.map(r=>`<option value="${r}" ${r===u.role?'selected':''}>${escapeHtml(ROLES[r]||r)}</option>`).join('')}</select></label><label><input id="editActive" type="checkbox" ${u.active?'checked':''} ${u.role==='ADMIN'?'disabled':''}> Tài khoản đang hoạt động</label><label>Mật khẩu mới<input id="editPassword" type="password" placeholder="Để trống nếu giữ nguyên"></label><div class="actions span"><button type="button" id="cancelUserEdit" class="secondary">HỦY</button><button class="primary">LƯU</button></div><div id="editUserMsg" class="message span" hidden></div></form></div></div>`);
  $('#cancelUserEdit').onclick=()=>$('#userEditorModal')?.remove();
  $('#editUserForm').onsubmit=async e=>{e.preventDefault();try{setBusy(true,'Đang cập nhật nhân sự…');await api('update-user',{id:u.id,employee_code:$('#editCode').value.trim(),full_name:$('#editName').value.trim(),contractor:$('#editContractor').value.trim(),role:$('#editRole').value||u.role,active:u.role==='ADMIN'?true:$('#editActive').checked,new_password:$('#editPassword').value});$('#userEditorModal')?.remove();await loadManagedUsers();}catch(err){message('#editUserMsg',err.message,'error');}finally{setBusy(false);}};
}

async function previewUsers(file){if(!file)return;try{validateFile(file);setBusy(true,'Đang đọc nhân sự…');const[rows,index]=await Promise.all([readWorkbook(file),api('admin-user-index')]),existing=new Set((index.employee_codes||[]).map(x=>String(x).toLowerCase())),parsed=parseUserRows(rows,existing);$('#userPreview').innerHTML=previewTable(parsed.slice(0,100),['employee_code','full_name','role','active'],`${parsed.length} nhân sự hợp lệ`)+`<button id="confirmUsers" class="primary">XÁC NHẬN IMPORT ${parsed.length} NHÂN SỰ</button>`;$('#confirmUsers').onclick=()=>importUsers(parsed);}catch(e){message('#userMsg',e.message,'error');}finally{setBusy(false);}}
async function importUsers(rows){try{setBusy(true,'Đang import nhân sự…');let done=0;const errors=[];for(let i=0;i<rows.length;i+=200){const r=await api('import-users',{items:rows.slice(i,i+200)});done+=Number(r.created||0)+Number(r.updated||0);errors.push(...(r.errors||[]));}if(errors.length)throw new Error(errors.slice(0,5).join('\n'));message('#userMsg',`Hoàn tất ${done} nhân sự.`,'good');$('#userPreview').innerHTML='';}catch(e){message('#userMsg',e.message,'error');}finally{setBusy(false);}}

async function renderConfig(){
  $('#content').innerHTML=`<div class="heading"><div><p class="eyebrow">ADMIN</p><h2>Cấu hình hệ thống</h2></div></div><form id="configForm" class="card form-grid"><label>Nhắc Invent nhận xử lý (phút)<input id="ackMinutes" type="number" min="1" max="480" required></label><label>Chu kỳ nhắc Invent (phút)<input id="reminderMinutes" type="number" min="1" max="480" required></label><label>Quá thời gian xử lý (phút)<input id="replenishMinutes" type="number" min="1" max="480" required></label><label>Nhắc Picker chưa ACK (phút)<input id="pickerAck" type="number" min="1" max="60" required></label><label>Lưu log server (ngày)<input id="logRetention" type="number" min="1" max="60" required></label><p class="muted span">Không có auto-SKIP: hết thời gian chỉ nhắc Invent, không tự cho Picker skip.</p><button class="primary">LƯU CẤU HÌNH</button><div id="configMsg" class="message span" hidden></div></form>`;
  try{const c=await api('get-config');$('#ackMinutes').value=c.acknowledge_minutes;$('#reminderMinutes').value=c.reminder_minutes;$('#replenishMinutes').value=c.replenish_minutes;$('#pickerAck').value=c.picker_ack_reminder_minutes;$('#logRetention').value=c.diagnostic_log_retention_days;}catch(e){message('#configMsg',e.message,'error');}
  $('#configForm').onsubmit=async e=>{e.preventDefault();try{setBusy(true,'Đang lưu cấu hình…');await api('save-config',{acknowledge_minutes:Number($('#ackMinutes').value),reminder_minutes:Number($('#reminderMinutes').value),replenish_minutes:Number($('#replenishMinutes').value),picker_ack_reminder_minutes:Number($('#pickerAck').value),diagnostic_log_retention_days:Number($('#logRetention').value)});message('#configMsg','Đã lưu cấu hình.','good');}catch(err){message('#configMsg',err.message,'error');}finally{setBusy(false);}};
}

function validateFile(file){if(!file.name.toLowerCase().endsWith('.xlsx'))throw new Error('Chỉ hỗ trợ file .xlsx');if(file.size>MAX_FILE_BYTES)throw new Error('File vượt quá 15 MB');}
async function readWorkbook(file){const ExcelJS=await getExcelJS(),wb=new ExcelJS.Workbook();await wb.xlsx.load(await file.arrayBuffer());const ws=wb.worksheets[0];if(!ws)throw new Error('File không có sheet');const rows=[];ws.eachRow({includeEmpty:false},row=>rows.push(row.values.slice(1).map(cellValue)));return rows;}
function cellValue(v){if(v==null)return'';if(typeof v==='object'){if('text'in v)return String(v.text);if('result'in v)return String(v.result??'');if(Array.isArray(v.richText))return v.richText.map(x=>x.text).join('');}return String(v).trim();}
function headerIndexes(row){const m=new Map();row.forEach((x,i)=>m.set(normalize(x),i));return m;}
function findHeader(map,...names){for(const n of names){const i=map.get(normalize(n));if(i!==undefined)return i;}throw new Error(`Thiếu cột ${names[0]}`);}
function parseSkuRows(rows){if(rows.length<2)throw new Error('File không có dữ liệu');const h=headerIndexes(rows[0]),si=findHeader(h,'sku','ma sku'),ni=findHeader(h,'ten san pham','ten hang','product name'),map=new Map();rows.slice(1).forEach((r,idx)=>{const sku=String(r[si]||'').trim(),name=String(r[ni]||'').trim();if(!sku&&!name)return;if(!sku||!name)throw new Error(`Dòng ${idx+2}: thiếu SKU hoặc tên sản phẩm`);if(map.has(sku)&&normalize(map.get(sku).product_name)!==normalize(name))throw new Error(`SKU ${sku} có nhiều tên khác nhau`);map.set(sku,{sku,product_name:name});});if(!map.size)throw new Error('Không có SKU hợp lệ');return[...map.values()];}
function parseUserRows(rows,existing){if(rows.length<2)throw new Error('File không có dữ liệu');const h=headerIndexes(rows[0]),ci=findHeader(h,'ma nhan vien','employee code'),ni=findHeader(h,'ho ten','full name'),ki=findHeader(h,'nha thau','contractor'),ri=findHeader(h,'vai tro','role'),ai=findHeader(h,'trang thai','active'),pi=findHeader(h,'mat khau khoi tao','initial password'),seen=new Set(),out=[];rows.slice(1).forEach((r,idx)=>{const line=idx+2,code=String(r[ci]||'').trim(),name=String(r[ni]||'').trim();if(!code&&!name)return;if(!code||!name)throw new Error(`Dòng ${line}: thiếu mã hoặc họ tên`);if(!/^[A-Za-z0-9._-]+$/.test(code))throw new Error(`Dòng ${line}: mã nhân viên không hợp lệ`);const key=code.toLowerCase();if(seen.has(key))throw new Error(`Mã ${code} bị trùng`);seen.add(key);const rr=parseRole(r[ri],line),active=parseActive(r[ai],line),pwd=String(r[pi]||'');if(!existing.has(key)&&pwd.length<8)throw new Error(`Dòng ${line}: tài khoản mới cần mật khẩu ít nhất 8 ký tự`);out.push({employee_code:code,full_name:name,contractor:String(r[ki]||'').trim(),role:rr,active,initial_password:pwd});});if(!out.length)throw new Error('Không có nhân sự hợp lệ');return out;}
function parseRole(v,line){const x=normalize(v).replace(/[ -]/g,'_');if(['picker','pick','nguoi_lay_hang'].includes(x))return'PICKER';if(['invent','invent_user','bao_hang_invent'].includes(x))return'INVENT';if(['admin_invent','invent_admin'].includes(x))return'ADMIN_INVENT';if(x==='admin')throw new Error(`Dòng ${line}: không được tạo ADMIN thứ hai`);throw new Error(`Dòng ${line}: quyền '${v}' không hợp lệ`);}
function parseActive(v,line){const x=normalize(v);if(['hoat dong','active','true','1','co'].includes(x))return true;if(['ngung','ngung hoat dong','inactive','false','0','khong'].includes(x))return false;throw new Error(`Dòng ${line}: trạng thái '${v}' không hợp lệ`);}
function previewTable(rows,fields,title){return`<div class="card"><h3>${escapeHtml(title)}</h3><div class="table-wrap"><table><thead><tr>${fields.map(f=>`<th>${escapeHtml(f)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${fields.map(f=>`<td>${escapeHtml(r[f])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>${rows.length>=100?'<p class="muted">Chỉ hiển thị 100 dòng đầu.</p>':''}</div>`;}
async function downloadSkuTemplate(){const ExcelJS=await getExcelJS(),wb=new ExcelJS.Workbook(),ws=wb.addWorksheet('SKU');ws.addRow(['SKU','Tên sản phẩm']);ws.addRow(['ABC123','Sản phẩm mẫu']);downloadBuffer(await wb.xlsx.writeBuffer(),'MAU_SKU_BAO_HANG_1291.xlsx');}
async function downloadUserTemplate(){const ExcelJS=await getExcelJS(),wb=new ExcelJS.Workbook(),ws=wb.addWorksheet('NHAN_SU');ws.addRow(['Mã nhân viên','Họ tên','Nhà thầu','Vai trò','Trạng thái','Mật khẩu khởi tạo']);ws.addRow(['10001','Nguyễn Văn Mẫu','Nội bộ','PICKER','Hoạt động','ChangeMe123']);ws.addRow(['10002','Invent Mẫu','Nội bộ','INVENT','Hoạt động','ChangeMe123']);ws.addRow(['10003','Admin Invent Mẫu','Nội bộ','ADMIN_INVENT','Hoạt động','ChangeMe123']);downloadBuffer(await wb.xlsx.writeBuffer(),'MAU_NHAN_SU_BAO_HANG_1291.xlsx');}
function downloadBuffer(buffer,name){const blob=new Blob([buffer],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function statusLabel(s){return({OPEN:'BÁO THIẾU',CLAIMED:'BÁO THIẾU',SEARCHING:'BÁO THIẾU',REPLENISHING:'BÁO THIẾU',AVAILABLE:'ĐÃ CHÂM BÙ',SKIP_ALLOWED:'ĐƯỢC SKIP',CLOSED:'ĐÃ ĐÓNG'})[s]||s;}
function formatTime(v){if(!v)return'—';try{return new Intl.DateTimeFormat('vi-VN',{dateStyle:'short',timeStyle:'short'}).format(new Date(v));}catch{return v;}}
function formatBytes(n){const v=Number(n||0);return v<1024?`${v} B`:`${(v/1024).toFixed(1)} KB`;}

state.session=readSession();if(state.session)renderApp();else renderLogin();
