create table if not exists public.staff_sync_audit (
  id bigint generated by default as identity primary key,
  run_id uuid not null references public.staff_sync_runs(id) on delete cascade,
  employee_code text,
  action text not null,
  before_row jsonb,
  after_row jsonb,
  success boolean not null,
  error text,
  created_at timestamptz not null default now()
);

create index if not exists staff_sync_audit_run_id_created_at_idx
  on public.staff_sync_audit (run_id, created_at);

alter table public.staff_sync_audit enable row level security;
revoke all on table public.staff_sync_audit from anon, authenticated;
grant all on table public.staff_sync_audit to service_role;
